# Generated by Django 5.2.6 on 2025-10-05 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomepageAnimation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='animations/')),
                ('animation_code', models.TextField(help_text='Paste animation code (e.g. JavaScript/CSS)')),
            ],
        ),
    ]
