# Generated by Django 5.2.6 on 2025-10-05 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_homepageanimation'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaticPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(choices=[('privacy', 'Privacy Policy'), ('terms', 'Terms & Conditions')], unique=True)),
                ('content', models.TextField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['slug'],
            },
        ),
        migrations.AddField(
            model_name='about',
            name='hero_image',
            field=models.ImageField(blank=True, null=True, upload_to='about/hero/'),
        ),
        migrations.AddField(
            model_name='about',
            name='mission',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='about',
            name='shop_details',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='about',
            name='short_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='about',
            name='subtitle',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='about',
            name='vision',
            field=models.TextField(blank=True),
        ),
    ]
