# Generated by Django 5.2.6 on 2025-10-05 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_staticpage_about_hero_image_about_mission_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staticpage',
            name='external_url',
            field=models.URLField(blank=True),
        ),
    ]
