# Generated by Django 5.2.6 on 2025-10-14 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
